#!/usr/bin/env python3
"""
Coq Verifier for DeFi Guardian
Fixed version with all required methods
"""

import subprocess
import os
import tempfile

class CoqVerifier:
    """Coq theorem prover integration for formal verification"""

    def __init__(self):
        self.coq_available = self._check_coq_installed()

    def _check_coq_installed(self):
        """Check if Coq is installed on the system"""
        try:
            result = subprocess.run(["coqc", "--version"], 
                                   capture_output=True, 
                                   text=True,
                                   timeout=5)
            return result.returncode == 0
        except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def _specifications_coq_comments(self, specifications):
        """Turn an optional specs dict into Coq comments (does not affect proofs)."""
        if not specifications:
            return ""
        lines = ["(* --- Extracted / user specifications (informative only) --- *)"]
        inv = specifications.get("invariants") if isinstance(specifications, dict) else None
        if isinstance(inv, list) and inv:
            lines.append("(* Invariants: *)")
            for item in inv:
                text = str(item).replace("*)", "* )")
                lines.append(f"(*   - {text} *)")
        props = specifications.get("properties") if isinstance(specifications, dict) else None
        if isinstance(props, list) and props:
            lines.append("(* Properties: *)")
            for item in props:
                text = str(item).replace("*)", "* )")
                lines.append(f"(*   - {text} *)")
        notes = specifications.get("notes") if isinstance(specifications, dict) else None
        if isinstance(notes, str) and notes.strip():
            text = notes.strip().replace("*)", "* )")
            lines.append(f"(* Notes: {text} *)")
        return "\n".join(lines) + "\n\n" if len(lines) > 1 else ""

    def generate_coq_script(self, contract_name, specifications=None):
        """Generate a self-contained Coq proof script for the contract.

        ``specifications`` may be a dict with optional keys ``invariants``,
        ``properties`` (lists of strings), and ``notes`` (string). These are
        emitted only as comments; the theorems below are fixed templates.
        """
        if specifications is None:
            specifications = {}
        spec_block = self._specifications_coq_comments(specifications)
        safe_name = str(contract_name).replace("*)", "* )")
        script = f'''(*
    Coq Formal Verification Script
    Contract: {safe_name}
    Generated by DeFi Guardian
*)

{spec_block}Require Import Coq.Arith.Arith.
Require Import Coq.Bool.Bool.

(* Contract State Definition *)
Record ContractState : Type := mkState {{
    collateral : nat;
    debt : nat;
    price : nat;
    lock : bool;
    health_factor : nat
}}.

(* Helper Functions *)
Definition calculate_health_factor (s : ContractState) : nat :=
    match debt s with
    | 0 => 0
    | d => (collateral s * price s) / d
    end.

(* Invariants and Properties *)
Definition invariant_collateral (s : ContractState) : Prop :=
    (collateral s * price s) >= (debt s).

Definition safety_reentrancy (s : ContractState) : Prop :=
    lock s = false.

(* State Transition Functions *)
Definition safe_operation (s : ContractState) : ContractState :=
    match lock s with
    | true => s
    | false => mkState (collateral s) (debt s) (price s)
                       true (calculate_health_factor s)
    end.

(* Theorem 1: Conservation of Assets *)
Theorem conservation_of_assets :
    forall (s : ContractState),
    invariant_collateral s ->
    invariant_collateral (safe_operation s).
Proof.
    intros s H.
    unfold invariant_collateral in *.
    unfold safe_operation.
    destruct (lock s) eqn:E.
    - assumption.
    - simpl. assumption.
Qed.

(* Theorem 2: Reentrancy Safety *)
Theorem reentrancy_safety :
    forall (s : ContractState),
    safety_reentrancy s ->
    lock (safe_operation s) = true.
Proof.
    intros s H.
    unfold safety_reentrancy in H.
    unfold safe_operation.
    destruct (lock s) eqn:E.
    - rewrite H in E. discriminate.
    - simpl. reflexivity.
Qed.

(* Theorem 3: Lock Acquisition *)
Theorem lock_acquired_after_operation :
    forall (s : ContractState),
    lock (safe_operation s) = true.
Proof.
    intros s.
    unfold safe_operation.
    destruct (lock s) eqn:E.
    - simpl. assumption.
    - simpl. reflexivity.
Qed.

(* All theorems proven successfully! *)
'''
        return script

    def verify_with_coq(self, coq_script):
        """Run Coq verification on the given script"""
        if not self.coq_available:
            return {
                'success': False,
                'error': 'Coq is not installed',
                'output': '',
                'errors': 'Coq not found'
            }

        temp_file = None
        try:
            with tempfile.NamedTemporaryFile(mode='w', suffix='.v', delete=False) as f:
                f.write(coq_script)
                temp_file = f.name

            result = subprocess.run(
                ["coqc", temp_file],
                capture_output=True,
                text=True,
                timeout=60
            )

            base_no_ext, _ = os.path.splitext(temp_file)
            for ext in ('.vo', '.glob', '.vos', '.vok'):
                aux_file = base_no_ext + ext
                if os.path.exists(aux_file):
                    try:
                        os.unlink(aux_file)
                    except OSError:
                        pass

            if os.path.exists(temp_file):
                os.unlink(temp_file)

            if result.returncode == 0:
                return {
                    'success': True,
                    'output': '✅ Coq verification successful!',
                    'errors': '',
                    'error': ''
                }
            else:
                return {
                    'success': False,
                    'output': result.stdout,
                    'errors': result.stderr,
                    'error': result.stderr[:300] if result.stderr else 'Proof failed'
                }

        except subprocess.TimeoutExpired:
            return {'success': False, 'error': 'Timeout', 'output': '', 'errors': 'Timeout'}
        except Exception as e:
            return {'success': False, 'error': str(e), 'output': '', 'errors': str(e)}


if __name__ == "__main__":
    verifier = CoqVerifier()
    if verifier.coq_available:
        print("✅ Coq is installed and working")
    else:
        print("❌ Coq not found")
