import subprocess
import os
import tempfile

class LeanVerifier:
    """Lean theorem prover integration"""
    
    def __init__(self):
        self.lean_available = self._check_lean_installed()
    
    def _check_lean_installed(self):
        """Check if Lean is installed"""
        try:
            subprocess.run(["lean", "--version"], capture_output=True, check=True)
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False
    
    def generate_lean_script(self, contract_name, specifications):
        lines = [
            "-- Lean 4 Proof Script for " + contract_name,
            "-- Generated by DeFi Guardian",
            "",
            "structure ContractState where",
            "  collateral   : Nat",
            "  debt         : Nat",
            "  price        : Nat",
            "  lock         : Bool",
            "  healthFactor : Nat",
            "",
            "def invariantCollateral (s : ContractState) : Prop :=",
            "  s.collateral * s.price >= s.debt",
            "",
            "def safeOperation (s : ContractState) : ContractState :=",
            "  if s.lock then s",
            "  else ContractState.mk s.collateral s.debt s.price true",
            "         ((s.collateral * s.price) / s.debt)",
            "",
            "theorem conservation (s : ContractState) (h : invariantCollateral s) :",
            "    invariantCollateral (safeOperation s) := by",
            "  unfold invariantCollateral safeOperation",
            "  split",
            "  . exact h",
            "  . simp",
            "    exact h",
            "",
            "theorem reentrancySafety (s : ContractState) (h : s.lock = false) :",
            "    (safeOperation s).lock = true := by",
            "  simp [safeOperation, h]",
        ]
        return "\n".join(lines)
    
    def verify_with_lean(self, lean_script):
        if not self.lean_available:
            return {'success': False, 'error': 'Lean not installed', 'output': ''}
        temp_file = None
        try:
            # lean --stdin is not supported in Lean 4; write to a real .lean file
            with tempfile.NamedTemporaryFile(mode='w', suffix='.lean', delete=False) as f:
                f.write(lean_script)
                temp_file = f.name

            result = subprocess.run(
                ["lean", temp_file],
                capture_output=True,
                text=True,
                timeout=60
            )
            return {
                'success': result.returncode == 0,
                'output': result.stdout,
                'errors': result.stderr if result.stderr else result.stdout
            }
        except subprocess.TimeoutExpired:
            return {'success': False, 'error': 'Lean timed out after 60 seconds — is lake/mathlib needed?', 'output': ''}
        except Exception as e:
            return {'success': False, 'error': str(e), 'output': ''}
        finally:
            if temp_file and os.path.exists(temp_file):
                try:
                    os.unlink(temp_file)
                except Exception:
                    pass
