import subprocess
import os
import tempfile

class LeanVerifier:
    """Lean theorem prover integration"""
    
    def __init__(self):
        self.lean_available = self._check_lean_installed()
    
    def _check_lean_installed(self):
        """Check if Lean is installed"""
        try:
            subprocess.run(["lean", "--version"], capture_output=True, check=True)
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False
    
    def generate_lean_script(self, contract_name, specifications):
        lean_script = f"""
-- Lean 4 Proof Script for {contract_name}
-- Generated by DeFi Guardian

structure ContractState where
  collateral   : Nat
  debt         : Nat
  price        : Nat
  lock         : Bool
  healthFactor : Nat

def invariantCollateral (s : ContractState) : Prop :=
  s.collateral * s.price ≥ s.debt

def safeOperation (s : ContractState) : ContractState :=
  if s.lock then s
  else {{ s with lock := true,
               healthFactor := (s.collateral * s.price) / s.debt }}

theorem conservation (s : ContractState) (h : invariantCollateral s) :
    invariantCollateral (safeOperation s) := by
  unfold invariantCollateral safeOperation
  split
  · exact h
  · simp; exact h

theorem reentrancySafety (s : ContractState) (h : s.lock = false) :
    (safeOperation s).lock = true := by
  simp [safeOperation, h]
"""
        return lean_script
    
    def verify_with_lean(self, lean_script):
        """Run Lean verification"""
        if not self.lean_available:
            return {
                'success': False,
                'error': 'Lean not installed. Please install Lean theorem prover.',
                'output': ''
            }
        
        try:
            # Create temporary .lean file
            with tempfile.NamedTemporaryFile(mode='w', suffix='.lean', delete=False) as f:
                f.write(lean_script)
                temp_file = f.name
            
            # Run Lean verification
            result = subprocess.run(
                ["lean", temp_file],
                capture_output=True,
                text=True,
                timeout=60
            )
            
            # Clean up
            os.unlink(temp_file)
            
            return {
                'success': result.returncode == 0,
                'output': result.stdout,
                'errors': result.stderr
            }
        except Exception as e:
            return {
                'success': False,
                'error': str(e),
                'output': ''
            }
