/* Translated from Rust with LTL Properties */
/* Generated by DeFi Guardian Formal Verification Suite */

/* === STATE VARIABLES === */
int lock = 0;
byte state = 0;

/* === LTL PROPERTIES === */
ltl safety_no_overflow { [] (lock >= 0 && lock <= 1) }
ltl liveness_progress { <> (state == 1) }
ltl invariant_stable { [] (state == 1 -> lock == 1) }

active proctype Program() {
    atomic {
        printf("Validating Rust State Machine...\n");
        state = 1;
    }
    
    do
        :: state == 1 -> atomic {
            printf("Executing program logic...\n");
            lock = 1;
            
            /* Verify invariants */
            assert(lock == 1);
            
            lock = 0;
            printf("Program execution complete.\n");
            state = 2;
            break;
        }
        :: state == 2 -> atomic {
            printf("Program terminated.\n");
            break;
        }
    od
}
